fix small bug with rustflags and add more CI to test very basic cases
dtolnay/cargo-docs-rs pull request #10
Opened 2024-03-01 09:22 UTC by jonaspleyer

This PR fixes some code duplication (see f7d3df9f22a1b84867155781b66ad881ce899682) and introduces multiple basic layouts to test various common examples of workspaces and custom rustdoc flags.

The `cargo_config_rustflags` example was failing for me before removing the duplicate code.

I am very happy about feedback.

PS: I have been using your libraries (like many people do) extensively and I very much appreciate the work that you do for the community.

2024-04-06 04:26 UTC, dtolnay requested changes
Thanks for the PR. I don't think this is the right fix &mdash; docs.rs _does_ pass `--config build.rustflags`, for example in this build: https://docs.rs/crate/proc-macro2/1.0.79/builds/1154848.

2024-04-07 20:09 UTC, jonaspleyer commented
> Thanks for the PR. I don't think this is the right fix — docs.rs _does_ pass `--config build.rustflags`, for example in this build: https://docs.rs/crate/proc-macro2/1.0.79/builds/1154848.

But there is some code duplication in lines 189 to 193 in `main.rs` which does not seem correct to me. The build you sent should still pass when applying my patch from commit f7d3df9f22a1b84867155781b66ad881ce899682.

2024-04-07 20:34 UTC, dtolnay commented
One of those is configuring build.rustflags and the other is configuring host.rustflags. They are not duplicated.

2024-04-08 05:32 UTC, jonaspleyer commented
This is clearly an oversight on my part and I see now why my initial attempt of fixing is wrong. I will probably come back to this. Are you still interested in the additional test cases?

2024-05-19 04:25 UTC, dtolnay reviewed
Feel free to open a new PR if you come back to this. I don't think I need these tests in this repo, but I am interested in fixes if you identify any bug.

2024-05-19 04:25 UTC, closed without merging